use demo;

create table CUSTOMER (
	id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(50),
	address VARCHAR(50),
	company_id MEDIUMINT NOT NULL,
	CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
