use demo;

create table COMPANY (
	id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	vat_reference VARCHAR(50),
	name VARCHAR(50),
	address VARCHAR(50),
	CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
